# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/currency-exchange-service/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-1'
        repository: 'vargheseibm'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest