apiVersion: v1
kind: ConfigMap
metadata:
  name: currency-configmap
data:
   CURRENCY_EXCHANGE_URI: http://currency-exchange
  
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion
spec:
  template:
    metadata:
      labels: 
        app: currency-conversion
    spec:
      containers:
        - name: currency-conversion-containers
          image: vargheseibm/mmv2-currency-conversion-service:0.0.11-SNAPSHOT
          ports:
            - containerPort: 8100
          envFrom:
            - configMapRef:
                name: currency-configmap
              valueFrom:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
      
---
apiVersion: v1
kind: Service
metadata:
  name: currency-conversion
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  selector:
    app: currency-conversion
    