FROM ubuntu:20.04 as build
 

ADD https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.zip . 

RUN apt-get update \ 
 && apt install -y openjdk-17-jdk \
 && apt install -y openjdk-17-jre \
 && apt install wget -y \
 && wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb \
 && apt install ./jdk-17_linux-x64_bin.deb -y \
 && update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk-17/bin/java" 1 \
 && update-alternatives --set java /usr/lib/jvm/jdk-17/bin/java \
 && apt-get install unzip \                                  
 && mkdir /opt/mvnd \                                        
 && unzip apache-maven-3.8.5-bin.zip \                       
 && mv apache-maven-3.8.5/* /opt/mvnd   


RUN java -version
RUN /opt/mvnd/bin/mvn  -version 

WORKDIR "/currency-exchange-service"
COPY pom.xml .
COPY src src

RUN /opt/mvnd/bin/mvn clean install \
&& /opt/mvnd/bin/mvn  package -Dmaven.test.skip                           

FROM ubuntu:20.04

COPY --from=build target/*.jar ./app.jar

EXPOSE 8080


CMD [ "java", "-jar","./app.jar" ]
========================
FROM openjdk:17.0.2-slim-buster

COPY target/*.jar ./app.jar

EXPOSE 8000 

CMD [ "java", "-jar","./app.jar" ]

 
